apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ecommerceweb
  name: ecommerce-web
  namespace: ecommerce
spec:
  ports:
  - port: {{.Values.service.spec.ports.port }}
    protocol: {{.Values.service.spec.ports.protocol}}
    targetPort: {{.Values.service.spec.ports.targetPort}}
    nodePort: {{.Values.service.spec.ports.nodePort}}
  selector:
    app: ecommerceweb
  type: {{.Values.service.spec.type}}
