service:
  spec:
    ports:
      port: 8899
      protocol: "TCP"
      targetPort: 8899
      nodePort: 30999
    type: "NodePort"

deployment:
  spec:
    template:
      spec:
        containers:
          image: "nandu9948/jenkins_webapp"
          name: "jenkins-webapp"
          ports:
            containerPort: 8899
          livenessProbe:
            httpGet:
              path: "/webApp/"
              port: 8899
            initialDelaySeconds: 40
            timeoutSeconds: 100
            periodSeconds: 10
            failureThreshold: 2
          readinessProbe:
            httpGet:
              path: "/webApp/"
              port: 8899
            initialDelaySeconds: 50
            timeoutSeconds: 600
            periodSeconds: 10
            failureThreshold: 1
          resources:
            requests:
              memory: "100Mi"
              cpu: "10m"
            limits:
              memory: "150Mi"
              cpu: "40m"

quotas:
  spec:
    hard:
      cpu: "500m"
      memory: "700Mi"
      pods: "6"

autoScaling:
  spec:
    scaleTargetRef:
      apiVersion: "apps/v1"
      kind: "Deployment"
      name: "ecommerce-web"
    minReplicas: 2
    maxReplicas: 5
    metrics:
      type: "Resource"
      resource:
        name: "cpu"
        target:
          type: "Utilization"
          averageUtilization: 80 


